Support SSL context
Kitware/wslink pull request #117
Opened 2022-08-23 14:16 UTC by BotellaA

On some cloud platforms (here AWS), we need the ssl/wss protocol to be used. 
aiohttp is able to handle such connexion but it was not accessible from the wslink API.

We also added the ability to create a temporary certificate.

fix #112

2022-08-23 14:55 UTC, jourdain commented on python/src/wslink/server.py
> +    server_config = {
I think the merge from master did not do a good job here. Please revisit that change as we changed the structure here to support reverse connection and from the diff it is hard to tell what is happening now... My guess it should be a more compact change.

2022-08-23 14:59 UTC, jourdain commented on python/src/wslink/server.py
> +    parser.add_argument(
Can you add some comment here on how to use that arg (i.e. example)? As I'm not sure how you pass the certificate and key.

2022-08-23 15:02 UTC, jourdain requested changes
Globally this looks really good.
- So far, I'm just worried for the `server.py` file as I would assume the change should be simpler and the issue is just because of the merge rather than doing the change directly from master.
- It would be nice to have some command line examples to make sure we know how to use the --ssl arg.

2022-08-24 14:30 UTC, jourdain commented
I love it, can you just squash all your changes and keep it under a single commit with your original commit message `feat(SSL): support ssl context`

2022-08-24 14:43 UTC, jourdain commented
Something weird happened in your single commit. Try rebasing it on master.

2022-08-24 14:50 UTC, BotellaA commented
Seems ok now

2022-08-24 14:50 UTC, merged

2022-08-24 14:51 UTC, jourdain commented
Yes thank you, this is awesome! I'll try to get it in pv 5.11.

2022-08-24 14:51 UTC, jourdain commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wslink/v/1.8.0)
- [GitHub release](https://github.com/Kitware/wslink/releases/tag/v1.8.0)
- `v1.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: